### ISSUE TITLE
Renommer en csv-detective-ml

### ISSUE THREAD

**Issue by abulte** [etalab/csv-detective-ml#1]
C'est un peu une lubie de ma part mais est-ce qu'on peut utiliser des `-` plutôt que des `_` dans le nom ? Et donc renommer aussi https://github.com/etalab/csv_detective pendant qu'on y est.

**Comment by psorianom** [comment]
D'accord. Je vois pas des problèmes avec le changement proposé.

**Comment by geoffreyaldebert** [comment]
@psorianom @abulte Done !
